Feature question component harshit
classganana/eduzy-dashboard pull request #4
Opened 2024-10-02 19:39 UTC by harshit120

2024-10-03 19:25 UTC, VenkataRavitejaGullapudi commented on src/components/question-component.jsx
> +
Rename this to .tsx (typescript-xml) file instead of .jsx

2024-10-03 19:25 UTC, VenkataRavitejaGullapudi commented on src/components/question-component.jsx
> +function QuestionComponent({ values, index }) {
After renaming, specify type to the props (Refer chapterCard.tsx component)
props should question and index
question should of type Question (This should be imported from types file)
index should of type number

2024-10-03 19:25 UTC, VenkataRavitejaGullapudi commented on src/components/question-component.jsx
> +      <p className={`ml-${index <= 9 ? "2" : "0"}`}>{index}.</p>
1. What is the need of this condition in className?
2. As index will start from 0, value should be index+1

2024-10-03 19:25 UTC, VenkataRavitejaGullapudi commented on src/components/question-component.jsx
> +                    correctAnswers.includes(option)
After adding the typings, you will understand what information we have in question that is passed.
Based on that please correct this logic accordingly.

To check the dummay data please refer chapterSlice.tsx file

2024-10-03 19:29 UTC, VenkataRavitejaGullapudi requested changes
Please complete the commented changes. And feel free to reachout to me if any help required.

2024-10-04 06:18 UTC, harshit120 commented on src/components/question-component.jsx
> +      <p className={`ml-${index <= 9 ? "2" : "0"}`}>{index}.</p>
As the index increases into double digits, ensure consistent vertical alignment of all questions by adjusting the left margin for two-digit numbers. This will maintain a clean and organized layout, ensuring that all questions lie in the same vertical line, assuming the total number of questions does not exceed 100.

2024-10-05 15:55 UTC, VenkataRavitejaGullapudi commented
Cool, changes are done as mentioned. Approving and merging this PR.

2024-10-05 15:55 UTC, VenkataRavitejaGullapudi approved these changes

2024-10-05 15:56 UTC, merged